# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Inkdrop.Inkdrop.Portable
PackageVersion: 5.8.1
PackageLocale: en-US
Publisher: Inkdrop
PublisherUrl: https://www.inkdrop.app/
PublisherSupportUrl: https://docs.inkdrop.app/contact
PrivacyUrl: https://docs.inkdrop.app/privacy
Author: Takuya Matsuyama
PackageName: Inkdrop
PackageUrl: https://www.inkdrop.app/
License: Proprietary
LicenseUrl: https://docs.inkdrop.app/terms
Copyright: © 2024 Inkdrop
CopyrightUrl: https://docs.inkdrop.app/terms
ShortDescription: A Note-taking App with Robust Markdown Editor
Moniker: inkdrop
Tags:
- note
- tech
- notes
- editor
- markdown
ReleaseNotesUrl: https://forum.inkdrop.app/t/inkdrop-desktop-v5-8-1/4587
PurchaseUrl: https://www.inkdrop.app/pricing/
Documentations:
- DocumentLabel: Inkdrop User Manual
  DocumentUrl: https://docs.inkdrop.app/
ManifestType: defaultLocale
ManifestVersion: 1.6.0
