# Created with komac v2.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: DuckStudio.FufuTools
PackageVersion: 1.3.1-1
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Custom: /verysilent /suppressmsgboxes
UpgradeBehavior: install
ReleaseDate: 2024-05-28
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/DuckDuckStudio/Fufu_Tools/releases/download/v1.3.1-1/Fufu_Tools_Setup.v1.3.1-1.exe
  InstallerSha256: 4D5015520355B8AF7FBF43CE1D32EE859919AE7505CAD114350EB45E70557F50
ManifestType: installer
ManifestVersion: 1.6.0
