# Created with komac v2.2.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: SABnzbdTeam.SABnzbd.Portable
PackageVersion: 4.2.3
PackageLocale: en-US
Publisher: The SABnzbd Team
PublisherUrl: https://github.com/sabnzbd/sabnzbd
Author: The SABnzbd Team
PackageName: SABnzbd Portable
PackageUrl: https://sabnzbd.org/
License: GPL2/GPL3
LicenseUrl: https://github.com/sabnzbd/sabnzbd/blob/HEAD/LICENSE.txt
Copyright: (c) Copyright 2007-2021 by "The SABnzbd-team" <team@sabnzbd.org>
CopyrightUrl: https://github.com/sabnzbd/sabnzbd/blob/develop/LICENSE.txt
ShortDescription: SABnzbd is an Open Source Binary Newsreader written in Python.
Tags:
- binary-newsreader
- python
- usenet
ReleaseNotesUrl: https://github.com/sabnzbd/sabnzbd/releases/tag/4.2.3
ManifestType: defaultLocale
ManifestVersion: 1.6.0
