# Created with komac v2.2.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: SABnzbdTeam.SABnzbd.Potable
PackageVersion: 4.2.3
InstallerType: zip
NestedInstallerFiles:
- RelativeFilePath: SABnzbd-4.2.3/SABnzbd-console.exe
- RelativeFilePath: SABnzbd-4.2.3/SABnzbd.exe
UpgradeBehavior: install
ReleaseDate: 2024-03-11
Installers:
- Architecture: x86
  NestedInstallerType: potable
  InstallerUrl: https://github.com/sabnzbd/sabnzbd/releases/download/4.2.3/SABnzbd-4.2.3-win32-bin.zip
  InstallerSha256: E486C0E82791919A65ED7E57C25E589BA7D5E8BCA8F6C38E77E3C8A75F4FB5B6
- Architecture: x64
  NestedInstallerType: potable
  InstallerUrl: https://github.com/sabnzbd/sabnzbd/releases/download/4.2.3/SABnzbd-4.2.3-win64-bin.zip
  InstallerSha256: 12E418875B597A14ADF4E52BA7314E7B153E38596D5077F9C3AFE111F8B7CBB3
ManifestType: installer
ManifestVersion: 1.6.0
