# Created with komac v2.2.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: yuyuanweb.jianqiebanzhushou
PackageVersion: '0.6'
PackageLocale: zh-CN
Publisher: 上海鱼鸢网络技术有限公司
PublisherUrl: https://www.yuyuanweb.com/
PackageName: 剪切助手
PackageUrl: https://jianqiezhushou.com/
License: Freeware
LicenseUrl: https://yuyuanweb.yuque.com/org-wiki-yuyuanweb-zvq1bg/dbtzac/pfvkwgp5lturc9ms
Copyright: Copyright © 2024 上海鱼鸢网络技术有限公司
ShortDescription: 遥遥领先的复制粘贴效率工具
Moniker: clipboard-assistant
Tags:
- clipboard
ManifestType: defaultLocale
ManifestVersion: 1.6.0
